// 화면 미리보기용 임시 데이터입니다.
// 실제 Supabase 연결(Phase 2) 이후에는 lib/queries/*.ts 의 실제 DB 조회로 대체됩니다.

export interface MockCategory {
  id: string;
  name: string;
  slug: string;
  isFeatured: boolean;
}

export const MOCK_CATEGORIES: MockCategory[] = [
  { id: "cat-1", name: "병원·외출 동행", slug: "hospital-outing", isFeatured: true },
  { id: "cat-2", name: "반려동물 돌봄", slug: "pet-care", isFeatured: true },
  { id: "cat-3", name: "집안일 도움", slug: "housework", isFeatured: true },
  { id: "cat-4", name: "정리수납", slug: "organizing", isFeatured: false },
  { id: "cat-5", name: "요리·반찬", slug: "cooking", isFeatured: false },
  { id: "cat-6", name: "디지털 생활 도움", slug: "digital-help", isFeatured: true },
  { id: "cat-7", name: "어르신 생활지원", slug: "senior-support", isFeatured: false },
  { id: "cat-8", name: "아이 생활지원", slug: "kids-support", isFeatured: true },
  { id: "cat-9", name: "취미·생활교육", slug: "hobby-education", isFeatured: false },
  { id: "cat-10", name: "행사·이사 도움", slug: "event-moving", isFeatured: false },
];

// 카테고리별 세부 서비스 항목. 제공자 등록/요청글 작성 폼에서 사용합니다.
export const SERVICE_ITEMS_BY_CATEGORY: Record<string, string[]> = {
  "hospital-outing": [
    "병원 동행",
    "약국 동행",
    "건강검진 동행",
    "주민센터 동행",
    "은행 동행",
    "산책 동행",
    "외출 동행",
  ],
  "pet-care": ["산책", "방문 돌봄", "식사와 물 챙기기", "배변 정리", "동물병원 동행"],
  housework: ["청소", "빨래", "설거지", "장보기", "간단한 음식 준비"],
  organizing: ["옷장 정리", "주방 정리", "냉장고 정리", "물건 분류", "이사 전후 정리"],
  cooking: ["집밥 만들기", "밑반찬 만들기", "식사 준비", "김장", "명절 음식"],
  "digital-help": [
    "스마트폰 사용",
    "키오스크 이용",
    "컴퓨터 기본 설정",
    "프린터 연결",
    "온라인 신청",
  ],
  "senior-support": ["말벗", "산책", "장보기", "식사 준비", "외출 동행", "일상생활 보조"],
  "kids-support": ["등하원 동행", "숙제 도움", "놀이 활동", "방학 생활지원"],
  "hobby-education": ["뜨개질", "재봉", "미술", "꽃꽂이", "한글", "컴퓨터 기초"],
  "event-moving": ["집들이 준비", "손님맞이", "포장", "짐 정리", "행사 후 정리"],
};

export interface MockProvider {
  id: string;
  headline: string;
  nickname: string;
  categorySlug: string;
  serviceItems: string[];
  experienceYears: number;
  experienceDescription: string;
  introduction: string;
  availableDays: string[];
  availableTimeText: string;
  availableServices: string;
  unavailableServices: string;
  contactMethod: "전화" | "카카오톡";
  contactValue: string;
  contactAvailableTime: string;
  status: "ACTIVE" | "PAUSED";
}

export const MOCK_PROVIDERS: MockProvider[] = [
  {
    id: "p-1",
    headline: "부모님 병원 동행 10년 경험으로 편안하게 함께해 드려요",
    nickname: "다정한손길",
    categorySlug: "hospital-outing",
    serviceItems: ["병원 동행", "약국 동행", "건강검진 동행"],
    experienceYears: 10,
    experienceDescription:
      "부모님을 10년간 간병하며 대형병원 접수, 진료 대기, 검사 동행을 도맡아 했습니다.",
    introduction: "천천히, 편안하게 병원 일정을 함께 챙겨드립니다.",
    availableDays: ["월", "화", "수", "목", "금"],
    availableTimeText: "평일 오전 9시 ~ 오후 5시",
    availableServices: "접수와 이동 동행, 진료 대기, 약국 동행, 귀가 동행",
    unavailableServices: "주사, 투약, 의료적 판단, 전문 간호, 의료 처치",
    contactMethod: "전화",
    contactValue: "010-1234-5678",
    contactAvailableTime: "평일 오전 9시 ~ 오후 6시",
    status: "ACTIVE",
  },
  {
    id: "p-2",
    headline: "건강검진, 은행 업무 동행도 편하게 도와드려요",
    nickname: "느티나무",
    categorySlug: "hospital-outing",
    serviceItems: ["건강검진 동행", "은행 동행", "주민센터 동행"],
    experienceYears: 7,
    experienceDescription: "행정업무 동행 경험 7년, 어르신들의 외출을 자주 도왔습니다.",
    introduction: "느긋하게, 서두르지 않고 함께 다녀요.",
    availableDays: ["화", "목", "토"],
    availableTimeText: "오전 10시 ~ 오후 4시",
    availableServices: "접수와 이동 동행, 진료 대기, 귀가 동행",
    unavailableServices: "주사, 투약, 의료적 판단, 전문 간호",
    contactMethod: "카카오톡",
    contactValue: "kakao_neutinamu",
    contactAvailableTime: "매일 오전 9시 ~ 오후 8시",
    status: "ACTIVE",
  },
  {
    id: "p-3",
    headline: "반려견 두 마리를 키운 경험으로 산책과 방문 돌봄을 도와드려요",
    nickname: "댕댕이이모",
    categorySlug: "pet-care",
    serviceItems: ["산책", "방문 돌봄", "식사와 물 챙기기"],
    experienceYears: 8,
    experienceDescription: "8년째 반려견 두 마리와 함께 살고 있어요.",
    introduction: "우리 아이를 키우듯 소중하게 돌봐드릴게요.",
    availableDays: ["월", "수", "금", "토", "일"],
    availableTimeText: "오전 8시 ~ 오후 8시",
    availableServices: "산책, 방문 돌봄, 식사와 물 챙기기, 배변 정리",
    unavailableServices: "장기 임시 보호, 전문 훈련, 의료 처치, 투약 대행",
    contactMethod: "전화",
    contactValue: "010-2345-6789",
    contactAvailableTime: "매일 오전 9시 ~ 오후 9시",
    status: "ACTIVE",
  },
  {
    id: "p-4",
    headline: "고양이 임시 돌봄과 병원 동행 도와드립니다",
    nickname: "냥냥집사",
    categorySlug: "pet-care",
    serviceItems: ["방문 돌봄", "동물병원 동행"],
    experienceYears: 5,
    experienceDescription: "고양이 3마리와 함께 5년째 생활하고 있습니다.",
    introduction: "예민한 아이들도 편안하게 대해요.",
    availableDays: ["화", "목", "토", "일"],
    availableTimeText: "오후 1시 ~ 오후 7시",
    availableServices: "방문 돌봄, 식사와 물 챙기기, 동물병원 동행",
    unavailableServices: "장기 임시 보호, 공격성이 강한 동물 돌봄",
    contactMethod: "카카오톡",
    contactValue: "kakao_nyangzip",
    contactAvailableTime: "매일 오후 12시 ~ 오후 9시",
    status: "ACTIVE",
  },
  {
    id: "p-5",
    headline: "이사와 살림 경험을 바탕으로 옷장과 주방 정리를 도와드려요",
    nickname: "정리하는날",
    categorySlug: "organizing",
    serviceItems: ["옷장 정리", "주방 정리", "이사 전후 정리"],
    experienceYears: 12,
    experienceDescription: "12년간 가정을 꾸리며 다진 정리·수납 노하우가 있습니다.",
    introduction: "공간이 훨씬 넓어 보이도록 깔끔하게 정리해드려요.",
    availableDays: ["월", "화", "수", "목"],
    availableTimeText: "오전 9시 ~ 오후 3시",
    availableServices: "옷장 정리, 주방 정리, 냉장고 정리, 물건 분류",
    unavailableServices: "이사 업체 포장 이사 대체 불가",
    contactMethod: "전화",
    contactValue: "010-3456-7890",
    contactAvailableTime: "평일 오전 9시 ~ 오후 5시",
    status: "ACTIVE",
  },
  {
    id: "p-6",
    headline: "집안 청소부터 간단한 정리까지 꼼꼼하게 도와드려요",
    nickname: "산뜻한하루",
    categorySlug: "housework",
    serviceItems: ["청소", "빨래", "장보기"],
    experienceYears: 9,
    experienceDescription: "9년간 살림을 도맡아 하며 청소와 정리에 자신이 있습니다.",
    introduction: "깨끗하고 산뜻한 공간을 만들어드릴게요.",
    availableDays: ["월", "수", "금"],
    availableTimeText: "오전 9시 ~ 오후 2시",
    availableServices: "청소, 빨래, 설거지, 장보기, 간단한 음식 준비",
    unavailableServices: "대형 이사 청소는 어려워요",
    contactMethod: "전화",
    contactValue: "010-4567-8901",
    contactAvailableTime: "평일 오전 9시 ~ 오후 3시",
    status: "PAUSED",
  },
  {
    id: "p-7",
    headline: "스마트폰이 어려운 분께 천천히 반복해서 알려드려요",
    nickname: "천천히알려드림",
    categorySlug: "digital-help",
    serviceItems: ["스마트폰 사용", "키오스크 이용"],
    experienceYears: 4,
    experienceDescription: "부모님께 스마트폰을 알려드리던 경험을 살려 도와드립니다.",
    introduction: "몇 번이고 천천히, 이해하실 때까지 알려드려요.",
    availableDays: ["화", "목"],
    availableTimeText: "오후 2시 ~ 오후 6시",
    availableServices: "스마트폰 사용, 키오스크 이용, 온라인 신청",
    unavailableServices: "전문 컴퓨터 수리는 어려워요",
    contactMethod: "카카오톡",
    contactValue: "kakao_chunchunhi",
    contactAvailableTime: "매일 오후 1시 ~ 오후 7시",
    status: "ACTIVE",
  },
  {
    id: "p-8",
    headline: "컴퓨터 기본 설정과 프린터 연결 도와드립니다",
    nickname: "디지털도우미",
    categorySlug: "digital-help",
    serviceItems: ["컴퓨터 기본 설정", "프린터 연결", "인터넷 신청"],
    experienceYears: 6,
    experienceDescription: "6년간 가족들의 컴퓨터와 스마트기기를 도맡아 챙겼습니다.",
    introduction: "복잡한 설정도 쉽게 풀어서 알려드려요.",
    availableDays: ["월", "화", "수", "목", "금"],
    availableTimeText: "오후 6시 ~ 오후 9시",
    availableServices: "컴퓨터 기본 설정, 프린터 연결, 온라인 신청",
    unavailableServices: "하드웨어 부품 교체는 어려워요",
    contactMethod: "전화",
    contactValue: "010-5678-9012",
    contactAvailableTime: "평일 오후 6시 ~ 오후 10시",
    status: "ACTIVE",
  },
  {
    id: "p-9",
    headline: "집밥과 밑반찬으로 든든한 한 끼를 채워드려요",
    nickname: "집밥한상",
    categorySlug: "cooking",
    serviceItems: ["집밥 만들기", "밑반찬 만들기"],
    experienceYears: 15,
    experienceDescription: "15년간 가족 식사를 챙겨온 손맛으로 정성껏 만들어드려요.",
    introduction: "집에서 먹는 것처럼 편안한 집밥을 만들어드립니다.",
    availableDays: ["월", "수", "금"],
    availableTimeText: "오전 10시 ~ 오후 2시",
    availableServices: "집밥 만들기, 밑반찬 만들기, 식사 준비",
    unavailableServices: "출장 연회 규모는 어려워요",
    contactMethod: "전화",
    contactValue: "010-6789-0123",
    contactAvailableTime: "평일 오전 9시 ~ 오후 4시",
    status: "ACTIVE",
  },
  {
    id: "p-10",
    headline: "어르신 말벗과 산책, 편안하게 곁에 있어드려요",
    nickname: "다정한이웃",
    categorySlug: "senior-support",
    serviceItems: ["말벗", "산책", "장보기"],
    experienceYears: 6,
    experienceDescription: "어르신들과 대화하고 함께 산책하는 걸 좋아합니다.",
    introduction: "편안한 말벗이 되어드릴게요.",
    availableDays: ["화", "목", "토"],
    availableTimeText: "오전 10시 ~ 오후 4시",
    availableServices: "말벗, 산책, 장보기, 식사 준비",
    unavailableServices: "전문 요양, 의료행위, 투약 관리, 목욕 보조",
    contactMethod: "카카오톡",
    contactValue: "kakao_dajeongiut",
    contactAvailableTime: "매일 오전 9시 ~ 오후 6시",
    status: "PAUSED",
  },
  {
    id: "p-11",
    headline: "등하원부터 숙제까지, 아이와 편안하게 함께해드려요",
    nickname: "다정한선생님",
    categorySlug: "kids-support",
    serviceItems: ["등하원 동행", "숙제 도움", "놀이 활동"],
    experienceYears: 9,
    experienceDescription: "9년간 두 아이를 키우며 등하원과 숙제 지도를 도맡아 했습니다.",
    introduction: "아이의 속도에 맞춰 천천히, 다정하게 챙겨드려요.",
    availableDays: ["월", "화", "수", "목", "금"],
    availableTimeText: "오후 2시 ~ 오후 7시",
    availableServices: "등하원 동행, 숙제 도움, 놀이 활동",
    unavailableServices: "영유아 단독 돌봄, 숙박 돌봄, 의료적 돌봄, 장시간 단독 보호",
    contactMethod: "전화",
    contactValue: "010-7890-1234",
    contactAvailableTime: "평일 오후 1시 ~ 오후 8시",
    status: "ACTIVE",
  },
  {
    id: "p-12",
    headline: "방학 동안 아이와 즐겁게 놀아주고 챙겨드려요",
    nickname: "방학지킴이",
    categorySlug: "kids-support",
    serviceItems: ["방학 생활지원", "놀이 활동", "숙제 도움"],
    experienceYears: 5,
    experienceDescription: "초등학생 자녀를 키운 경험으로 방학 생활지원을 도와드립니다.",
    introduction: "심심하지 않게, 안전하게 방학을 함께 보내드려요.",
    availableDays: ["화", "목", "토", "일"],
    availableTimeText: "오전 9시 ~ 오후 5시",
    availableServices: "방학 생활지원, 놀이 활동, 숙제 도움",
    unavailableServices: "영유아 단독 돌봄, 숙박 돌봄, 의료적 돌봄, 장시간 단독 보호",
    contactMethod: "카카오톡",
    contactValue: "kakao_banghak_zikimi",
    contactAvailableTime: "매일 오전 9시 ~ 오후 6시",
    status: "ACTIVE",
  },
];

export interface MockRequest {
  id: string;
  title: string;
  categorySlug: string;
  serviceItem: string | null;
  content: string;
  desiredDate: string;
  desiredTime: string;
  durationText: string;
  budgetText: string;
  isNegotiable: boolean;
  isUrgent: boolean;
  contactMethod: "전화" | "카카오톡";
  contactValue: string;
  status: "OPEN" | "CLOSED";
  createdAt: string;
}

export const MOCK_REQUESTS: MockRequest[] = [
  {
    id: "r-1",
    title: "어머니 병원 동행 부탁드려요 (내일 오전)",
    categorySlug: "hospital-outing",
    serviceItem: "병원 동행",
    content:
      "어머니가 내일 오전 대학병원 진료가 있으신데 저는 회사 일정 때문에 함께 가기 어렵습니다. 접수와 진료 대기, 귀가까지 동행해주실 분을 찾습니다.",
    desiredDate: "2026-07-21",
    desiredTime: "오전 9시",
    durationText: "약 3시간",
    budgetText: "5만원",
    isNegotiable: true,
    isUrgent: true,
    contactMethod: "전화",
    contactValue: "010-9111-2222",
    status: "OPEN",
    createdAt: "2026-07-20",
  },
  {
    id: "r-2",
    title: "강아지 하루 방문 돌봄 구합니다",
    categorySlug: "pet-care",
    serviceItem: "방문 돌봄",
    content:
      "당일 출장 때문에 강아지를 잠깐 돌봐주실 분을 찾습니다. 산책과 식사만 챙겨주시면 됩니다.",
    desiredDate: "2026-07-22",
    desiredTime: "오후 1시 ~ 오후 6시",
    durationText: "약 5시간",
    budgetText: "협의 가능",
    isNegotiable: true,
    isUrgent: false,
    contactMethod: "카카오톡",
    contactValue: "kakao_needhelp1",
    status: "OPEN",
    createdAt: "2026-07-19",
  },
  {
    id: "r-3",
    title: "이사 후 옷장·주방 정리 도와주실 분",
    categorySlug: "organizing",
    serviceItem: "이사 전후 정리",
    content: "이사한 지 얼마 안 돼 짐 정리가 막막합니다. 옷장과 주방 위주로 부탁드려요.",
    desiredDate: "2026-07-25",
    desiredTime: "오전 10시",
    durationText: "약 4시간",
    budgetText: "8만원",
    isNegotiable: false,
    isUrgent: false,
    contactMethod: "전화",
    contactValue: "010-9333-4444",
    status: "OPEN",
    createdAt: "2026-07-18",
  },
  {
    id: "r-4",
    title: "부모님 스마트폰 사용법 알려주실 분",
    categorySlug: "digital-help",
    serviceItem: "스마트폰 사용",
    content: "부모님이 스마트폰 사용을 어려워하셔서 천천히 알려주실 분을 찾습니다.",
    desiredDate: "2026-07-23",
    desiredTime: "오후 3시",
    durationText: "약 2시간",
    budgetText: "3만원",
    isNegotiable: true,
    isUrgent: false,
    contactMethod: "카카오톡",
    contactValue: "kakao_needhelp4",
    status: "OPEN",
    createdAt: "2026-07-19",
  },
  {
    id: "r-5",
    title: "집 청소 정기적으로 도와주실 분 (마감)",
    categorySlug: "housework",
    serviceItem: "청소",
    content: "이미 도와주실 분을 찾아 마감되었습니다.",
    desiredDate: "2026-07-15",
    desiredTime: "오전 10시",
    durationText: "약 3시간",
    budgetText: "6만원",
    isNegotiable: false,
    isUrgent: false,
    contactMethod: "전화",
    contactValue: "010-9555-6666",
    status: "CLOSED",
    createdAt: "2026-07-10",
  },
  {
    id: "r-6",
    title: "급하게 반찬 몇 가지만 부탁드려요",
    categorySlug: "cooking",
    serviceItem: "밑반찬 만들기",
    content: "갑자기 손님이 오셔서 밑반찬 몇 가지가 급하게 필요합니다.",
    desiredDate: "2026-07-21",
    desiredTime: "오전 중",
    durationText: "약 2시간",
    budgetText: "4만원",
    isNegotiable: true,
    isUrgent: true,
    contactMethod: "전화",
    contactValue: "010-9777-8888",
    status: "OPEN",
    createdAt: "2026-07-20",
  },
  {
    id: "r-7",
    title: "방학 동안 아이 놀이·숙제 봐주실 분 구합니다",
    categorySlug: "kids-support",
    serviceItem: "방학 생활지원",
    content:
      "초등학생 아이가 방학이라 오후 시간 동안 놀이와 숙제를 봐주실 분을 찾습니다. 등하원은 필요 없습니다.",
    desiredDate: "2026-07-24",
    desiredTime: "오후 2시 ~ 오후 6시",
    durationText: "약 4시간",
    budgetText: "협의 가능",
    isNegotiable: true,
    isUrgent: false,
    contactMethod: "카카오톡",
    contactValue: "kakao_needhelp7",
    status: "OPEN",
    createdAt: "2026-07-19",
  },
];
